"""auto vote

Revision ID: 7f4a934aea71
Revises: 2c9d76045ec1
Create Date: 2025-09-15 13:09:02.147250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f4a934aea71'
down_revision: Union[str, Sequence[str], None] = '2c9d76045ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id',sa.Integer(),nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'],['posts.id'],ondelete="CASCADE"),
    sa.ForeignKeyConstraint(['user_id'],['users.id'],ondelete="CASCADE"),
    sa.PrimaryKeyConstraint('user_id','post_id')


    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('votes')
    
    # ### end Alembic commands ###
